### ISSUE TITLE
Error: BrowserModule has already been loaded.

### ISSUE THREAD

**Issue by danielkuhlwein** [vmudigal/ngx-audio-player#9]
After importing NgxAudioPlayerModule to my shared.module.ts, Angular throws this error:

`core.js:5847 ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

It seems as though it might be conflicting with one of the other modules already imported into shared.module.ts?

`imports: [
	CommonModule,
	MaterialModule,
	ReactiveFormsModule,
	RouterModule,
	ImageCropperModule,
	NgxAudioPlayerModule
]`

**Comment by vmudigal** [comment]
Never came across this issue. Did you find the root cause?

**Comment by danielkuhlwein** [comment]
Unfortunately I did not. I ended up just using HTML5's audio tag instead.

If I have time in the future I can try creating a reproducible stackblitz or something if you want to check it out for yourself 👍🏻

**Comment by keschra** [comment]
I have the same problem since I did the update from version 9.0.7 to 9.1.0
I have a shared module where i have imported the ngx audio player, the shared module is imported to all other sub modules. The player it self is used in 2 different submodules. 
If i just import the player to the app.module everything is working but i get a compiltion error:

1. If 'mat-advanced-audio-player' is an Angular component and it has 'displayTitle' input, then verify that it is part of this module.
    2. If 'mat-advanced-audio-player' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

This is my error message:
core.js:6228 ERROR Error: Uncaught (in promise): Error: NgxAudioPlayerModule is already loaded. Import it in the AppModule only
Error: NgxAudioPlayerModule is already loaded. Import it in the AppModule only
    at new NgxAudioPlayerModule (ngx-audio-player.js:927)
    at Object.NgxAudioPlayerModule_Factory [as factory] (ngx-audio-player.js:940)
    at R3Injector.hydrate (core.js:17193)
    at R3Injector.get (core.js:16943)
    at core.js:16989
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (core.js:16985)
    at new NgModuleRef$1 (core.js:36316)
    at NgModuleFactory$1.create (core.js:36415)
    at MapSubscriber.project (router.js:6507)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)

**Comment by keschra** [comment]
@vmudigal can you check this please?

**Comment by vmudigal** [comment]
> @vmudigal can you check this please?

@keschra This has been taken care in 9.1.1. Could you please upgrade the version?
Thanks.

**Comment by nangio2019** [comment]
I fixed this 

> I have the same problem since I did the update from version 9.0.7 to 9.1.0
> I have a shared module where i have imported the ngx audio player, the shared module is imported to all other sub modules. The player it self is used in 2 different submodules.
> If i just import the player to the app.module everything is working but i get a compiltion error:
> 
> 1. If 'mat-advanced-audio-player' is an Angular component and it has 'displayTitle' input, then verify that it is part of this module.
>    2. If 'mat-advanced-audio-player' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
>    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
> 
> This is my error message:
> core.js:6228 ERROR Error: Uncaught (in promise): Error: NgxAudioPlayerModule is already loaded. Import it in the AppModule only
> Error: NgxAudioPlayerModule is already loaded. Import it in the AppModule only
> at new NgxAudioPlayerModule (ngx-audio-player.js:927)
> at Object.NgxAudioPlayerModule_Factory [as factory] (ngx-audio-player.js:940)
> at R3Injector.hydrate (core.js:17193)
> at R3Injector.get (core.js:16943)
> at core.js:16989
> at Set.forEach ()
> at R3Injector._resolveInjectorDefTypes (core.js:16985)
> at new NgModuleRef$1 (core.js:36316)
> at NgModuleFactory$1.create (core.js:36415)
> at MapSubscriber.project (router.js:6507)
> at resolvePromise (zone-evergreen.js:798)
> at resolvePromise (zone-evergreen.js:750)
> at zone-evergreen.js:860
> at ZoneDelegate.invokeTask (zone-evergreen.js:399)
> at Object.onInvokeTask (core.js:41632)
> at ZoneDelegate.invokeTask (zone-evergreen.js:398)
> at Zone.runTask (zone-evergreen.js:167)
> at drainMicroTaskQueue (zone-evergreen.js:569)

I fixed : by removing BrowserAnimationsModule in ngx-audio-player.module.ts and build lib.

**Comment by adrian5632** [comment]
The issue still persists. It becomes apparent when we use lazy loaded modules. From what I understood, BrowserAnimationsModule should not be imported by libraries - this should only be imported once by the *app's root module* - if you need to deal with animations, perhaps NoopAnimationsModule would be a choice?
